# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: cinder 2015.1.dev303\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-01-30 06:25+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: cinder/api/__init__.py:31
msgid ""
"The v1 api is deprecated and will be removed after the Juno release. You "
"should set enable_v1_api=false and enable_v2_api=true in your cinder.conf"
" file."
msgstr ""

#: cinder/api/extensions.py:276
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/backup/api.py:142
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG backup "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/backup/api.py:154
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create backups (%(d_consumed)d "
"backups already consumed)"
msgstr ""

#: cinder/backup/driver.py:212
msgid ""
"Destination volume type is different from source volume type for an "
"encrypted volume. Encrypted backup restore has failed."
msgstr ""

#: cinder/backup/manager.py:610
#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is "
"not verified. Skipping verify."
msgstr ""

#: cinder/backup/drivers/ceph.py:1188
#, python-format
msgid ""
"RBD image for backup %(backup)s of volume %(volume)s not found. Deleting "
"backup metadata."
msgstr ""

#: cinder/backup/drivers/swift.py:582
msgid "swift error while listing objects, continuing with delete"
msgstr ""

#: cinder/backup/drivers/swift.py:591
#, python-format
msgid "swift error while deleting object %s, continuing with delete"
msgstr ""

#: cinder/brick/initiator/connector.py:237
#, python-format
msgid ""
"ISCSI volume not yet found at: %(host_device)s. Will rescan & retry.  Try"
" number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:644
#, python-format
msgid "Fibre volume not yet found. Will rescan & retry.  Try number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:788
#, python-format
msgid "AoE volume not yet found at: %(path)s. Try number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:870
msgid ""
"Connection details not present. RemoteFsClient may not initialize "
"properly."
msgstr ""

#: cinder/brick/initiator/linuxfc.py:51 cinder/brick/initiator/linuxfc.py:57
msgid "systool is not installed"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:118
#: cinder/brick/initiator/linuxscsi.py:126
#: cinder/brick/initiator/linuxscsi.py:143
#, python-format
msgid "multipath call failed exit (%(code)s)"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:166
#, python-format
msgid "Couldn't find multipath device %(line)s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:274
#, python-format
msgid "Took %s seconds to get logical volume info."
msgstr ""

#: cinder/brick/local_dev/lvm.py:373
#, python-format
msgid "Took %s seconds to get volume groups."
msgstr ""

#: cinder/common/sqlalchemyutils.py:67
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/db/sqlalchemy/api.py:214
#, python-format
msgid "Deadlock detected when running '%(func_name)s': Retrying..."
msgstr ""

#: cinder/db/sqlalchemy/api.py:867
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/image/glance.py:133
msgid ""
"glance_num_retries shouldn't be a negative value. The number of retries "
"will be set to 0 until this iscorrected in the cinder.conf."
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:78
msgid ""
"config option keymgr.fixed_key has not been defined: some operations may "
"fail unexpectedly"
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:134
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: cinder/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)s run outlasted interval by %(delay).2f sec"
msgstr ""

#: cinder/openstack/common/policy.py:258
#, python-format
msgid "Can not find policy directory: %s"
msgstr ""

#: cinder/openstack/common/service.py:356
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:400
#, python-format
msgid "No weighed hosts found for volume with properties: %s"
msgstr ""

#: cinder/scheduler/host_manager.py:461
#, python-format
msgid "volume service is down. (host: %s)"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:62
#, python-format
msgid ""
"Insufficient free space for volume creation on host %(host)s (requested /"
" avail): %(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:56
msgid ""
"No 'volume_backend_name' key in extra_specs. Skipping volume backend name"
" check."
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:60
#, python-format
msgid ""
"Volume backend names do not match: '%(target)s' vs '%(current)s' :: "
"Skipping"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:67
msgid "Filter function not set :: passing host"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:76
#, python-format
msgid "Error in filtering function '%(function)s' : '%(error)s' :: failing host"
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:96
#, python-format
msgid "Hint \"%s\" dropped because ExtendedServerAttributes not active in Nova."
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:107
#, python-format
msgid ""
"Hint \"%s\" dropped because Nova did not return enough information. "
"Either Nova policy needs to be changed or a privileged account for Nova "
"should be specified in conf."
msgstr ""

#: cinder/scheduler/weights/goodness.py:54
msgid "Goodness function not set :: defaulting to minimal goodness rating of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:62
#, python-format
msgid ""
"Error in goodness_function function '%(function)s' : '%(error)s' :: "
"Defaulting to a goodness of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:73
#, python-format
msgid ""
"Invalid goodness result.  Result must be between 0 and 100.  Result "
"generated: '%s' :: Defaulting to a goodness of 0"
msgstr ""

#: cinder/tests/test_fujitsu.py:176
msgid "method is not exist "
msgstr ""

#: cinder/tests/test_netapp_nfs.py:360
#, python-format
msgid "Share %(share)s and file name %(file_name)s"
msgstr ""

#: cinder/volume/driver.py:918
#: cinder/volume/drivers/fujitsu/eternus_dx_iscsi.py:150
#: cinder/volume/targets/iscsi.py:131
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/manager.py:183
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:841
#, python-format
msgid "Deleting image %(image_id)s in %(image_status)s state."
msgstr ""

#: cinder/volume/manager.py:847
#, python-format
msgid "Error occurred while deleting image %s."
msgstr ""

#: cinder/volume/manager.py:1240
#, python-format
msgid ""
"Unable to update stats, %(driver_name)s -%(driver_version)s "
"%(config_group)s driver is uninitialized."
msgstr ""

#: cinder/volume/manager.py:1628
#, python-format
msgid ""
"Unable to update volume replication status, %(driver_name)s "
"-%(driver_version)s %(config_group)s driver is uninitialized."
msgstr ""

#: cinder/volume/qos_specs.py:199
#, python-format
msgid "Failed to associate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:213
#, python-format
msgid "Failed to disassociate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:227
#, python-format
msgid "Failed to disassociate qos specs %s."
msgstr ""

#: cinder/volume/utils.py:279
msgid "Failed to create blkio cgroup"
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:118
#, python-format
msgid "got disconnected; trying to reconnect. (%s)"
msgstr ""

#: cinder/volume/drivers/eqlx.py:392
#, python-format
msgid "Volume %s was not found while trying to delete it."
msgstr ""

#: cinder/volume/drivers/eqlx.py:507
#, python-format
msgid "Volume %s is not found!, it may have been deleted."
msgstr ""

#: cinder/volume/drivers/glusterfs.py:184
#, python-format
msgid "Failed to refresh mounts, reason=%s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:273 cinder/volume/drivers/quobyte.py:191
#: cinder/volume/drivers/remotefs.py:216
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/lvm.py:168
#, python-format
msgid "Unable to update stats on non-initialized Volume Group: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:329 cinder/volume/drivers/srb.py:752
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:599 cinder/volume/drivers/lvm.py:616
msgid ""
"LVMISCSIDriver is deprecated, you should now just use LVMVolumeDriver and"
" specify target_helper for the target driver you wish to use."
msgstr ""

#: cinder/volume/drivers/nfs.py:331 cinder/volume/drivers/remotefs.py:484
#, python-format
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access). This is considered an insecure NAS environment. Please see"
" %s for information on a secure NFS configuration."
msgstr ""

#: cinder/volume/drivers/nfs.py:352 cinder/volume/drivers/remotefs.py:477
#, python-format
msgid ""
"The NAS file operations will be run as root: allowing root level access "
"at the storage backend. This is considered an insecure NAS environment. "
"Please see %s for information on a secure NAS configuration."
msgstr ""

#: cinder/volume/drivers/pure.py:208
#, python-format
msgid "Volume deletion failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:259
#, python-format
msgid ""
"iSCSI discovery of port %(port_name)s at %(port_portal)s failed with "
"error: %(err_msg)s"
msgstr ""

#: cinder/volume/drivers/pure.py:314
#, python-format
msgid "Volume connection already exists with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:434
#, python-format
msgid "Unable to delete Protection Group: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:485
#, python-format
msgid "Unable to delete Protection Group Snapshot: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:587
#, python-format
msgid "Volume unmanage was unable to rename the volume, error message: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:106
#, python-format
msgid ""
"There's no Quobyte volume configured (%s). Example: quobyte://<DIR "
"host>/<volume name>"
msgstr ""

#: cinder/volume/drivers/quobyte.py:335
#, python-format
msgid "Exception during mounting %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:394
#, python-format
msgid "Failed to unmount previous mount: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:398
#, python-format
msgid "Unknown error occurred while checking mount point: %s Trying to continue."
msgstr ""

#: cinder/volume/drivers/quobyte.py:416 cinder/volume/drivers/remotefs.py:444
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/quobyte.py:429
#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:178
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:833
msgid "volume_tmp_dir is now deprecated, please use image_conversion_dir"
msgstr ""

#: cinder/volume/drivers/remotefs.py:294
#, python-format
msgid "%(path)s is being set with open permissions: %(perm)s"
msgstr ""

#: cinder/volume/drivers/smbfs.py:208 cinder/volume/drivers/ibm/ibmnas.py:287
#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr ""

#: cinder/volume/drivers/smbfs.py:230
msgid "qemu-img is not installed."
msgstr ""

#: cinder/volume/drivers/solidfire.py:431
#: cinder/volume/drivers/fusionio/ioControl.py:254
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:618
msgid "Requested image is not accesible by current Tenant."
msgstr ""

#: cinder/volume/drivers/srb.py:83
#, python-format
msgid "Retrying failed call to %(func)s, attempt %(attempt)i."
msgstr ""

#: cinder/volume/drivers/srb.py:362
msgid "Configuration variable srb_base_urls not set or empty."
msgstr ""

#: cinder/volume/drivers/srb.py:606
#, python-format
msgid "All attempts to recover failed detach of %(volume)s failed."
msgstr ""

#: cinder/volume/drivers/srb.py:669
#, python-format
msgid "Removed volume group %s still appears in vgs."
msgstr ""

#: cinder/volume/drivers/srb.py:868
#, python-format
msgid "Volume %r not found while trying to remove."
msgstr ""

#: cinder/volume/drivers/srb.py:871
#, python-format
msgid "Error while removing export: %r"
msgstr ""

#: cinder/volume/drivers/symantec_cnfs.py:80
#, python-format
msgid "Snapshot %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/xio.py:471
#, python-format
msgid "IOnetworks GET failed (%d)"
msgstr ""

#: cinder/volume/drivers/xio.py:601
#, python-format
msgid "Could not get status for %(name)s (%(status)d)."
msgstr ""

#: cinder/volume/drivers/xio.py:609
msgid "No volume node in XML content."
msgstr ""

#: cinder/volume/drivers/xio.py:617
#, python-format
msgid "No status payload for volume %s."
msgstr ""

#: cinder/volume/drivers/xio.py:707
#, python-format
msgid "Volume %(name)s already presented (%(status)d)!"
msgstr ""

#: cinder/volume/drivers/xio.py:984
#, python-format
msgid "Could not get pool information (%s)!"
msgstr ""

#: cinder/volume/drivers/xio.py:1224
#, python-format
msgid "Delete volume: %s not found!"
msgstr ""

#: cinder/volume/drivers/zadara.py:465
#, python-format
msgid "snapshot: original volume %s not found, skipping delete operation"
msgstr ""

#: cinder/volume/drivers/zadara.py:473
#, python-format
msgid "snapshot: snapshot %s not found, skipping delete operation"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:214
#, python-format
msgid "Logout error: %(c)d %(r)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:443
#, python-format
msgid "delete_volume: unable to find volume %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:499
#, python-format
msgid "ScServerOperatingSystem GetList return: %(c)d %(r)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:742
msgid "Inconsistent Luns."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:157
#, python-format
msgid "Unable to locate volume:%s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:689
msgid ""
"The VMAX plugin only supports Retype.  If a pool based migration is "
"necessary this will happen on a Retype From the command line: cinder "
"--os-volume-api-version 2 retype <volumeId> <volumeType> --migration-"
"policy on-demand"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:723
#, python-format
msgid ""
"Failed to migrate: %(volumeName)s from default source storage group for "
"FAST policy: %(sourceFastPolicyName)s Attempting cleanup... "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:749
#, python-format
msgid ""
"Attempting a rollback of: %(volumeName)s to original pool "
"%(sourcePoolInstanceName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:780
#, python-format
msgid "_migrate_rollback on : %(volumeName)s from "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:818
#, python-format
msgid "_migrate_cleanup on : %(volumeName)s from "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2171
#, python-format
msgid ""
"Pre check for deletion Volume: %(volumeName)s is part of a storage group "
"Attempting removal from %(storageGroupInstanceName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:143
#, python-format
msgid ""
"Volume: %(volumeName)s Does not belong to storage storage group "
"%(defaultSgGroupName)s. "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:404
msgid "Unable to get storage tiers from tier policy rule."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:187
#: cinder/volume/drivers/emc/emc_vmax_masking.py:729
#, python-format
msgid "Volume: %(volumeName)s is already part of storage group %(sgGroupName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:258
#, python-format
msgid ""
"The volume is already part of storage group: "
"%(storageGroupInstanceName)s. "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:666
#: cinder/volume/drivers/emc/emc_vmax_masking.py:934
#, python-format
msgid "Unable to find Masking view: %(view)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:852
#, python-format
msgid "No storage group found. %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1439
#, python-format
msgid "No target ports found in masking view %(maskingView)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1485
#, python-format
msgid "No port group found in masking view %(mv)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:334
#, python-format
msgid "LUN already exists, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:362
#, python-format
msgid "LUN is already deleted, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:409
#, python-format
msgid "LUN %(name)s is already expanded. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:466
#, python-format
msgid "Consistency group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:535
#, python-format
msgid "CG %(cg_name)s does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:539
#, python-format
msgid "CG %(cg_name)s is deleting. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:565
#, python-format
msgid "Cgsnapshot name %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:583
#, python-format
msgid "Snapshot %(name)s for consistency group does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:604
#, python-format
msgid "Snapshot %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:624
#, python-format
msgid "Snapshot %(name)s may deleted already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:631
#, python-format
msgid "Snapshot %(name)s is in use, retry. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:658
#, python-format
msgid "Mount point %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:677
#, python-format
msgid ""
"Snapshot %(snapname)s is attached to snapshot mount point %(mpname)s "
"already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:731
#, python-format
msgid ""
"Migration command may get network timeout. Double check whether migration"
" in fact started successfully. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:742
#, python-format
msgid "Start migration failed. Message: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:825
#, python-format
msgid "Storage group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:842
#, python-format
msgid ""
"Storage group %(name)s doesn't exist, may have already been deleted. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:874
#, python-format
msgid ""
"Host %(host)s has already disconnected from storage group %(sgname)s. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:894
#, python-format
msgid ""
"LUN %(lun)s has already added to Storage Group %(sgname)s. Message: "
"%(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:914
#, python-format
msgid "HLU %(hlu)s has already been removed from %(sgname)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1069
msgid "No array serial number returned, set as unknown."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1248
#, python-format
msgid "See unavailable iSCSI target: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1454
msgid ""
"destroy_empty_storage_group: True. Empty storage group will be deleted "
"after volume is detached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1617
msgid ""
"Failed to get target_pool_name and target_array_serial. 'location_info' "
"is not in host['capabilities']."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1630
msgid "Error on parsing target_pool_name/target_array_serial."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1748
msgid "Storage-assisted migration failed during retype."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2105
#, python-format
msgid "Storage Group %s is not found. Create it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2436
#, python-format
msgid "Storage Group %s is not found. terminate_connection() is unnecessary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2444
#, python-format
msgid "Volume %s is not found. It has probably been removed in VNX."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2452
#, python-format
msgid "Volume %(vol)s was not in Storage Group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2470
#, python-format
msgid "Failed to destroy Storage Group %s."
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:88
#, python-format
msgid "object %(key)s of type %(typ)s not found"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:242
msgid "terminate_connection: lun map not found"
msgstr ""

#: cinder/volume/drivers/fujitsu/eternus_dx_common.py:792
#, python-format
msgid ""
"Snapshot: %(snapshot)s: volume: %(volume)s. Snapshot deleted but cleanup "
"timed out."
msgstr ""

#: cinder/volume/drivers/fujitsu/eternus_dx_common.py:805
#, python-format
msgid ""
"Snapshot: %(snapshot)s: volume: %(volume)s. Snapshot deleted but error "
"during cleanup. Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/hds/iscsi.py:594
msgid "terminate_conn: provider location empty."
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_common.py:392
#: cinder/volume/drivers/hitachi/hbsd_common.py:399
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1421
#, python-format
msgid "Failed to restart horcm: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_fc.py:184
#, python-format
msgid "Failed to add host group: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:897
#, python-format
msgid "Failed to discard zero page: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1396
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1406
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1414
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1440
#, python-format
msgid "Failed to create pair: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_snm2.py:129
#, python-format
msgid "ldev(%(ldev)d) is already mapped (hlun: %(hlu)d)"
msgstr ""

#: cinder/volume/drivers/huawei/__init__.py:75
#, python-format
msgid ""
"Product name %s is deprecated, update your configuration to the new "
"product name."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_t.py:353
#, python-format
msgid "_remove_iscsi_port: iSCSI port was not found on host %(hostid)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_t.py:582
#, python-format
msgid "_remove_fc_ports: FC port was not found on host %(hostid)s."
msgstr ""

#: cinder/volume/drivers/huawei/rest_common.py:252
msgid "Can't find lun or lungroup on the array."
msgstr ""

#: cinder/volume/drivers/huawei/rest_common.py:420
#: cinder/volume/drivers/huawei/rest_common.py:422
msgid "Can't find snapshot on the array."
msgstr ""

#: cinder/volume/drivers/huawei/rest_common.py:602
#, python-format
msgid "Failure deleting the snapshot %(snapshot_id)s of volume %(volume_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/rest_common.py:1163
msgid "Can't find lun on the array."
msgstr ""

#: cinder/volume/drivers/huawei/rest_common.py:1479
#, python-format
msgid "Unable to access config file. %s"
msgstr ""

#: cinder/volume/drivers/huawei/rest_common.py:1544
#: cinder/volume/drivers/huawei/rest_common.py:1553
msgid "Can't find target iqn from rest."
msgstr ""

#: cinder/volume/drivers/huawei/ssh_common.py:281
#, python-format
msgid ""
"_parse_volume_type: Unacceptable parameter %(key)s. Please check this key"
" in extra_specs and make it consistent with the element in configuration "
"file %(conf)s."
msgstr ""

#: cinder/volume/drivers/huawei/ssh_common.py:1122
#, python-format
msgid "remove_map: No map between host %(host)s and volume %(volume)s."
msgstr ""

#: cinder/volume/drivers/huaweistorhyper/utils.py:89
#, python-format
msgid "Invalid ip, ip address is: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:370
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:407
#, python-format
msgid "_execute_command_and_parse_attributes: Failed to run command: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:608
#, python-format
msgid "_get_vdisk_map_properties: Did not find a preferred node for vdisk %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:850
msgid "_remove_device: invalid properties or device."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:903
#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to any host "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:909
#, python-format
msgid ""
"_unmap_vdisk_from_host: Multiple mappings of volume %(vdisk_name)s found,"
" no host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:370
msgid "CHAP secret exists for host but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:415
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s"
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:466
#, python-format
msgid ""
"Unable to find a preferred node match for node %(node)s in the list of "
"available WWPNs on %(host)s. Using first available."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:771
#, python-format
msgid "Volume %s does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:344
#, python-format
msgid "unmap_vol_from_host: No mapping of volume %(vol_name)s to any host found."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:350
#, python-format
msgid ""
"unmap_vol_from_host: Multiple mappings of volume %(vol_name)s found, no "
"host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:362
#, python-format
msgid ""
"unmap_vol_from_host: No mapping of volume %(vol_name)s to host %(host)s "
"found."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:59
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:131
#, python-format
msgid "Extra spec %(old)s is obsolete.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:136
#, python-format
msgid "Extra spec %(old)s is deprecated.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:126
#, python-format
msgid "Could not determine root volume name on %s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:307
msgid "Volume refresh job already running. Returning..."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:314
#, python-format
msgid "Error refreshing volume info. Message: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:163
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:240
#, python-format
msgid ""
"Exception while registering image %(image_id)s in cache. Exception: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:308
#, python-format
msgid "Exception during cache cleaning %(share)s. Message - %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:366
#, python-format
msgid "Exception during deleting %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:425
#, python-format
msgid "Unexpected exception during image cloning in share %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:516
msgid "Discover file retries exhausted."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:574
msgid "Unexpected exception while short listing used share."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:637
#, python-format
msgid "Destination %s already exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:645
#, python-format
msgid "Exception moving file %(src)s. Message - %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:110
#, python-format
msgid "Exception creating vol %(name)s on share %(share)s. Details: %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:244
msgid "No shares found hence skipping ssc refresh."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:506
msgid "ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:518
msgid "refresh stale ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:621
#, python-format
msgid ""
"The user does not have access or sufficient privileges to use all netapp "
"APIs. The following extra_specs will fail or be ignored: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_7mode.py:129
#, python-format
msgid "Error finding LUNs for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:112
#, python-format
msgid "Error mapping LUN. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:125
#, python-format
msgid "Error unmapping LUN. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:333
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:133
#, python-format
msgid ""
"Production use of \"%(backend)s\" backend requires the Cinder controller "
"to have multipathing properly set up and the configuration option "
"\"%(mpflag)s\" to be set to \"True\"."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:433
msgid "Snapshot volume not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:474
#, python-format
msgid "Failure deleting job %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:477
#, python-format
msgid "Volume copy job for src vol %s not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:491
#, python-format
msgid "Failure deleting temp snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:536
#, python-format
msgid "Snapshot %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:643
#, python-format
msgid "Unable to update host type for host with label %(l)s. %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:648
#, python-format
msgid "Message - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:769
#, python-format
msgid "No storage pool found with available capacity %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:802
msgid "Returning as clean tmp vol job already running."
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:181
#, python-format
msgid "Cannot delete snapshot %(origin)s: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:207
#: cinder/volume/drivers/nexenta/nfs.py:208
#, python-format
msgid "Failed to delete zfs snapshot %(volume_name)s@%(name)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:269
#, python-format
msgid "Remote NexentaStor appliance at %s should be SSH-bound."
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:289
#, python-format
msgid ""
"Cannot send source snapshot %(src)s to destination %(dst)s. Reason: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:297
#, python-format
msgid ""
"Cannot delete temporary source snapshot %(src)s on NexentaStor Appliance:"
" %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:303
#, python-format
msgid "Cannot delete source volume %(volume)s on NexentaStor Appliance: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:313
#, python-format
msgid ""
"Cannot delete temporary destination snapshot %(dst)s on NexentaStor "
"Appliance: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:552
#, python-format
msgid ""
"Got error trying to destroy target group %(target_group)s, assuming it is"
" already gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:560
#, python-format
msgid ""
"Got error trying to delete target %(target)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:149
#, python-format
msgid "Cannot destroy created folder: %(vol)s/%(folder)s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:179
#, python-format
msgid "Cannot destroy cloned folder: %(vol)s/%(folder)s"
msgstr ""

#: cinder/volume/drivers/prophetstor/dpl_iscsi.py:153
#, python-format
msgid "Cannot get volume status %(exc)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1176
#, python-format
msgid "Flexvisor failed to delete volume %(id)s from the group %(vgid)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1181
#, python-format
msgid ""
"Flexvisor failed to delete volume %(id)s from group %(vgid)s due to "
"%(status)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1350
#, python-format
msgid "Failed to query pool %(id)s status %(ret)d."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:404
#, python-format
msgid "Failed to manage virtual volume %(disp)s due to error during retype."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:440
msgid ""
"Host exists without CHAP credentials set and has iSCSI attachments but "
"CHAP is enabled.  Updating host with new CHAP credentials."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:473
msgid "Host has no CHAP key, but CHAP is enabled."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:477
msgid "No host or VLUNs exist. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:505
msgid "Non-iSCSI VLUN detected."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:509
msgid "No VLUN contained CHAP credentials. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:437
#, python-format
msgid "CHAP secret exists for host %s but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:440
#, python-format
msgid "CHAP is enabled, but server secret not configured on server %s"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:187
#, python-format
msgid "Lun create for %s failed!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:212
#, python-format
msgid "Lun %s has dependent snapshots, skipping."
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:442
#: cinder/volume/drivers/violin/v6000_iscsi.py:471
msgid "Failed to receive update for total_gb stat!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:447
#: cinder/volume/drivers/violin/v6000_iscsi.py:476
msgid "Failed to receive update for free_gb stat!"
msgstr ""

#: cinder/volume/drivers/vmware/api.py:245
#, python-format
msgid ""
"Current session: %(session)s is inactive; re-creating the session while "
"invoking method %(module)s.%(method)s."
msgstr ""

#: cinder/volume/drivers/vmware/api.py:271
#, python-format
msgid "Error occurred while checking whether the current session: %s is active."
msgstr ""

#: cinder/volume/drivers/vmware/datastore.py:218
#, python-format
msgid "Unable to fetch datastores connected to host %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:197
msgid ""
"The VMware ESX VMDK driver is now deprecated and will be removed in the "
"Juno release. The VMware vCenter VMDK driver will remain and continue to "
"be supported."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:472
#, python-format
msgid ""
"Ignoring storage profile %s requirement for this volume since policy "
"based placement is disabled."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:588
#, python-format
msgid ""
"Unable to find suitable datastore for volume of size: %(vol)s GB under "
"host: %(host)s. More details: %(excep)s"
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:629
#, python-format
msgid ""
"Unable to find suitable datastore for volume: %(vol)s under host: "
"%(host)s. More details: %(excep)s"
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:678
#, python-format
msgid "Trying to boot from an empty volume: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:947
#, python-format
msgid "Error occurred while deleting temporary disk: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1033
#, python-format
msgid "Error occurred while deleting descriptor: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1062
#, python-format
msgid "Error occurred while deleting backing: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1403
#, python-format
msgid "Volume: %s is in use, can't retype."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1472
#, python-format
msgid ""
"There are no datastores matching new requirements; can't retype volume: "
"%s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1524
#, python-format
msgid ""
"Changing backing: %(backing)s name from %(new_name)s to %(old_name)s "
"failed."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1754
#, python-format
msgid ""
"Cannot undo volume rename; old name was %(old_name)s and new name is "
"%(new_name)s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1858
#, python-format
msgid "PBM WSDL file %s is missing!"
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:136
msgid "zfssa_initiator_config not found. Using deprecated configuration options."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:141
#, python-format
msgid ""
"zfssa_initiator: %(ini)s wont be used on zfssa_initiator_group= "
"%(inigrp)s."
msgstr ""

#: cinder/volume/targets/lio.py:36
msgid ""
"The lio_initiator_iqns option has been deprecated and no longer has any "
"effect."
msgstr ""

#: cinder/volume/targets/tgt.py:94
msgid "Attempting recreate of backing lun..."
msgstr ""

#: cinder/volume/targets/tgt.py:203
#, python-format
msgid "Persistence file already exists for volume, found file at: %s"
msgstr ""

#: cinder/volume/targets/tgt.py:233
#, python-format
msgid "Could not create target because it already exists for volume: %s"
msgstr ""

#: cinder/volume/targets/tgt.py:361
#, python-format
msgid "Volume path %s does not exist, nothing to remove."
msgstr ""

#: cinder/volume/targets/tgt.py:395
msgid "Silent failure of target removal detected, retry...."
msgstr ""

#: cinder/zonemanager/utils.py:78
msgid "Driver didn't return connection info, can't add zone."
msgstr ""

#: cinder/zonemanager/utils.py:103
msgid "Driver didn't return connection info from terminate_connection call."
msgstr ""

